package com.gyorik.junctionx.domain;

import java.util.ArrayList;
import java.util.List;

public enum Skill {
    ADMINISTRATIVE("Administrative"),
    BUSINESS_ANALYST("Business Analyst"),
    BUSINESS_DEVELOPMENT("Business Development"),
    BUSINESS_INTELLIGENCE("Business Intelligence"),
    BUSINESS_MANAGER("Business Manager"),
    CONSULTING("Consulting"),
    EXECUTIVE_ASSISTANT("Executive Assistant"),
    HUMAN_RESOURCES("Human Resources"),
    MANAGEMENT("Management"),
    NOTARY("Notary"),
    OFFICE_ASSISTANT("Office Assistant"),
    PERSONAL_ASSISTANT("Personal Assistant"),
    RECEPTIONIST("Receptionist"),
    TRAINING_COORDINATOR("Training Coordinator"),
    ADVERTISING("Advertising"),
    ART_CURATOR("Art Curator"),
    BROADCASTER("Broadcaster"),
    CONTENT_MANAGER("Content Manager"),
    CONTENT_STRATEGIST("Content Strategist"),
    DIGITAL_MEDIA("Digital Media"),
    EDITING("Editing"),
    FASHION_DESIGN("Fashion Design"),
    FASHION_BUYER("Fashion Buyer"),
    GRAPHIC_DESIGN("Graphic Design"),
    INTERIOR_DESIGN("Interior Design"),
    MAKEUP_ARTIST("Makeup Artist"),
    MUSEUM_CURATOR("Museum Curator"),
    PHOTOGRAPHY("Photography"),
    PUBLIC_RELATIONS("Public Relations"),
    SOCIAL_MEDIA("Social Media"),
    WEB_DESIGN("Web Design"),
    WRITING("Writing"),
    CAREER_COUNSELOR("Career Counselor"),
    COLLEGE_ADMISSIONS("College Admissions"),
    COLLEGE_PROFESSOR("College Professor"),
    FUNDRAISER("Fundraiser"),
    LAW_ENFORCEMENT_SKILLS("Law Enforcement Skills"),
    LEGAL("Legal"),
    LIBRARIAN("Librarian"),
    POLICY_ANALYST("Policy Analyst"),
    SCHOOL_PSYCHOLOGIST("School Psychologist"),
    SOCIAL_WORK("Social Work"),
    TEACHING("Teaching"),
    ACCOUNTING("Accounting"),
    BANKING("Banking"),
    BOOKKEEPING("Bookkeeping"),
    CHIEF_FINANCIAL_OFFICER("Chief Financial Officer"),
    CLAIMS_ADJUSTER("Claims Adjuster"),
    FINANCE("Finance"),
    INSURANCE("Insurance"),
    INVESTMENT_BANKING_ANALYST("Investment Banking Analyst"),
    UNDERWRITER("Underwriter"),
    CERTIFIED_NURSING_ASSISTANT("Certified Nursing Assistant"),
    CHIROPRACTOR("Chiropractor"),
    COUNSELING("Counseling"),
    DENTAL_ASSISTANT("Dental Assistant"),
    DENTIST("Dentist"),
    HOME_HEALTH_AIDE("Home Health Aide"),
    MASSAGE_THERAPIST("Massage Therapist"),
    MEDICAL_ASSISTANT("Medical Assistant"),
    MEDICAL_SECRETARY("Medical Secretary"),
    NURSING("Nursing"),
    NURSING_ASSISTANT("Nursing Assistant"),
    OPTICIAN("Optician"),
    ORTHODONTIST("Orthodontist"),
    PEDIATRICIAN("Pediatrician"),
    PHARMACIST("Pharmacist"),
    PHARMACY_TECHNICIAN("Pharmacy Technician"),
    PHLEBOTOMIST("Phlebotomist"),
    PHYSICAL_THERAPY_ASSISTANT("Physical Therapy Assistant"),
    PHYSICAL_THERAPIST("Physical Therapist"),
    PHYSICIAN("Physician"),
    PHYSICIAN_ASSISTANT("Physician Assistant"),
    RESPIRATORY_THERAPIST("Respiratory Therapist"),
    SPEECH_PATHOLOGIST("Speech Pathologist"),
    ULTRASOUND_TECHNICIAN("Ultrasound Technician"),
    VETERINARY_TECHNICIAN("Veterinary Technician"),
    RADIOLOGIC_TECHNOLOGIST("Radiologic Technologist"),
    ANDROID_DEVELOPER("Android Developer"),
    BIG_DATA("Big Data"),
    COMPUTER("Computer"),
    COMPUTER_PROGRAMMING("Computer Programming"),
    DATA_SCIENTIST("Data Scientist"),
    INFORMATION_SECURITY_ANALYST("Information Security Analyst"),
    INFORMATION_TECHNOLOGY("Information Technology"),
    IOS_DEVELOPER("iOS Developer"),
    IT_MANAGER("IT Manager"),
    IT_SOFT_SKILLS("IT Soft Skills"),
    PRODUCT_MANAGER("Product Manager"),
    PROJECT_MANAGER("Project Manager"),
    SEO("SEO"),
    SCRUM_MASTER("Scrum Master"),
    SOFTWARE_DEVELOPER("Software Developer"),
    SOFTWARE_ENGINEER("Software Engineer"),
    QUALITY_ASSURANCE("Quality Assurance"),
    TECH_SUPPORT("Tech Support"),
    TECHNICAL_SUPPORT_ENGINEER("Technical Support Engineer"),
    INSIDE_SALES("Inside Sales"),
    MARKET_RESEARCH_ANALYST("Market Research Analyst"),
    MARKETING("Marketing"),
    PHARMACEUTICAL_SALES("Pharmaceutical Sales"),
    REAL_ESTATE("Real Estate"),
    RETAIL("Retail"),
    SALES("Sales"),
    SALES_ASSOCIATE("Sales Associate"),
    BARISTA("Barista"),
    BARTENDER("Bartender"),
    BEAUTICIAN("Beautician"),
    CASHIER("Cashier"),
    CHEF("Chef"),
    CONCIERGE("Concierge"),
    CUSTODIAN("Custodian"),
    CUSTOMER_SERVICE("Customer Service"),
    ESTHETICIAN("Esthetician"),
    FLIGHT_ATTENDANT("Flight Attendant"),
    GARDENING("Gardening"),
    HAIR_STYLIST("Hair Stylist"),
    HOSPITALITY_INDUSTRY("Hospitality Industry"),
    GUEST_SERVICES_SKILLS("Guest Services Skills"),
    PERSONAL_TRAINER("Personal Trainer"),
    PILOT("Pilot"),
    RESTAURANT_AND_FOOD_SERVICE("Restaurant and Food Service"),
    HOSTESS("Hostess"),
    SERVER("Server"),
    TRAVEL_AGENT("Travel Agent"),
    WAITER("Waiter"),
    AIRCRAFT_MECHANIC("Aircraft Mechanic"),
    AUTOMOTIVE("Automotive"),
    BOILERMAKER("Boilermaker"),
    BRICK_MASON("Brick Mason"),
    CARPENTRY("Carpentry"),
    CONSTRUCTION("Construction"),
    ELECTRICIAN("Electrician"),
    HEAVY_EQUIPMENT_OPERATOR("Heavy Equipment Operator"),
    MACHINIST("Machinist"),
    MAINTENANCE_AND_JANITORIAL("Maintenance and Janitorial"),
    PAINTER("Painter"),
    PLUMBER("Plumber"),
    SURVEYOR("Surveyor"),
    TRUCK_DRIVER("Truck Driver"),
    WELDER("Welder"),
    ARCHITECT("Architect"),
    BIOMEDICAL_ENGINEER("Biomedical Engineer"),
    CIVIL_ENGINEER("Civil Engineer"),
    ENGINEERING("Engineering"),
    MECHANICAL_ENGINEER("Mechanical Engineer"),
    METEOROLOGIST("Meteorologist"),
    RESEARCH_ASSISTANT("Research Assistant");

    private final String summary;

    Skill(String _summary)
    {
        this.summary = _summary;
    }

    public String toString()
    {
        return summary;
    }
}
